name: Build BetterBatteryStats Debug APK

on:
  workflow_dispatch:  # 仅手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ 设置 JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 3️⃣ 缓存 Gradle
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 4️⃣ 显示所有可用 Gradle 任务
      - name: List all Gradle tasks
        run: ./gradlew tasks --all

      # 5️⃣ 构建 debug APK 或 bundle
      - name: Build APK / Bundle
        run: |
          ./gradlew assembleDebug || ./gradlew bundleDebug

      # 6️⃣ 列出生成的 APK / AAB
      - name: List build outputs
        run: find build/outputs/ -type f \( -name "*.apk" -o -name "*.aab" \) -exec ls -lh {} \;

      # 7️⃣ 上传 APK / AAB 文件为 artifact
      - name: Upload APK / AAB
        uses: actions/upload-artifact@v4
        with:
          name: BetterBatteryStats-build
          path: build/outputs/**/*.{apk,aab}
          
